<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['VanillaCMS']['Installed'] = '0';

$Configuration['VanillaCMS']['Copyright'] = '© '.date('Y').' Vanilla CMS by <a href="http://jockegustin.se">Jocke Gustin</a>';