<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['VanillaCMS']['Installed'] = '0';

$Configuration['VanillaCMS']['Copyright'] = '© '.date('Y').' Vanilla CMS by <a href="http://jockegustin.se">Jocke Gustin</a>';
//Prevent application from saving over routes to vanilla core-applications
$Configuration['VanillaCMS']['ReservedUrlCodes'] = array(
                                                   'discussions' => 'All discussions',
                                                   'discussion' => 'Single Discusson',
                                                   'categories' => 'Forum Categories',
                                                   'activity' => 'Recent Activity',
                                                   'messages' => 'Conversations application',
                                                   'profile' => 'Profile Page',
                                                   'search' => 'Search',
                                                   'dashboard' => 'Dashboard',
                                                   'entry' => 'Sign in/out'
                                                   );
//Core functions that are allowed to create menu-items
$Configuration['VanillaCMS']['CoreTemplates'] = array(
                                                   'discussions' => 'All discussions',
                                                   'categories/all' => 'Forum Categories',
                                                   'activity' => 'Recent Activity',
                                                   'messages/all' => 'Inbox',
                                                   'profile' => 'Profile',
                                                   'search' => 'Search',
                                                   'dashboard/settings' => 'Dashboard',
                                                   //'entry' => 'Sign in/out'
                                                   );   
//Core modules to add to modules list
$Configuration['VanillaCMS']['DashboardModules'] = array(
                                                      'GuestModule' => array(
                                                                           'Name' => 'Guest Module',
                                                                           'Description' => 'Displays info about login/signup',
                                                                           'HelpText' => 'Test',
                                                                           'ShowAssets' => true,
                                                                           'ContentType' => 'none',
                                                                           'ApplicationFolder' => 'dashboard',
                                                                           'ConfigSetting' => 'Garden.Modules.ShowGuestModule'
                                                      ),
                                                      'RecentActivityModule' => array(
                                                                           'Name' => 'Recent Activity',
                                                                           'Description' => 'Displays site-wide recent activity',
                                                                           'HelpText' => 'No of activities to display',
                                                                           'ShowAssets' => true,
                                                                           'ContentType' => 'text',
                                                                           'ApplicationFolder' => 'dashboard',
                                                                           'GetData' => 1
                                                      ),
                                                      'RecentUserModule' => array(
                                                                           'Name' => 'Recent Users',
                                                                           'Description' => 'Displays recent users',
                                                                           'HelpText' => 'No of users to display',
                                                                           'ShowAssets' => true,
                                                                           'ContentType' => 'text',
                                                                           'ApplicationFolder' => 'dashboard',
                                                                           'ConfigSetting' => 'Garden.Modules.ShowRecentUserModule'
                                                      )
                                                   );
$Configuration['VanillaCMS']['VanillaModules'] = array(
                                                   'CategoriesModule' => array(
                                                                        'Name' => 'Forum Categories',
                                                                        'Description' => 'Displays forum categories',
                                                                        'HelpText' => '',
                                                                        'ShowAssets' => true,
                                                                        'ContentType' => 'none',
                                                                        'ApplicationFolder' => 'vanilla'
                                                   ),
                                                   'BookmarkedModule' => array(
                                                                        'Name' => 'Forum Bookmarks',
                                                                        'Description' => 'Displays current users bookmarked discussions',
                                                                        'HelpText' => '',
                                                                        'ShowAssets' => true,
                                                                        'ContentType' => 'none',
                                                                        'ApplicationFolder' => 'vanilla',
                                                                        'ConfigSetting' => 'Vanilla.Modules.ShowBookmarkedModule'
                                                   ),
                                                   'NewDiscussionModule' => array(
                                                                        'Name' => 'New discussion button',
                                                                        'Description' => 'Displays button for creating new discussion',
                                                                        'HelpText' => '',
                                                                        'ShowAssets' => true,
                                                                        'ContentType' => 'none',
                                                                        'ApplicationFolder' => 'vanilla'
                                                   ),
                                                   'DiscussionsModule' => array(
                                                                        'Name' => 'Forum Discussions',
                                                                        'Description' => 'Displays most recent discussions',
                                                                        'HelpText' => 'No of discussions to display',
                                                                        'ShowAssets' => true,
                                                                        'ContentType' => 'text',
                                                                        'ApplicationFolder' => 'vanilla',
                                                                        'GetData' => 1
                                                   )
                                                   );                           